//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtobufMsg.proto
namespace ProtobufMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessagePackage")]
  public partial class MessagePackage : global::ProtoBuf.IExtensible
  {
    public MessagePackage() {}
    
    private int _protoid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"protoid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int protoid
    {
      get { return _protoid; }
      set { _protoid = value; }
    }
    private byte[] _protodata;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"protodata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] protodata
    {
      get { return _protodata; }
      set { _protodata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CaterpillarPullRequest")]
  public partial class CaterpillarPullRequest : global::ProtoBuf.IExtensible
  {
    public CaterpillarPullRequest() {}
    
    private string _clientname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientname
    {
      get { return _clientname; }
      set { _clientname = value; }
    }
    private string _shapes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"shapes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string shapes
    {
      get { return _shapes; }
      set { _shapes = value; }
    }
    private string _imgstyles;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"imgstyles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string imgstyles
    {
      get { return _imgstyles; }
      set { _imgstyles = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CaterpillarPullResponse")]
  public partial class CaterpillarPullResponse : global::ProtoBuf.IExtensible
  {
    public CaterpillarPullResponse() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatRequest")]
  public partial class HeartBeatRequest : global::ProtoBuf.IExtensible
  {
    public HeartBeatRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatResponse")]
  public partial class HeartBeatResponse : global::ProtoBuf.IExtensible
  {
    public HeartBeatResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}